# # server:
# #   port: 7000

# spring:
#     application:
#         name: mall-coupon
#     # datasource:
#     #     username: root
#     #     password: root
#     #     url: jdbc:mysql://192.168.56.10:3306/mall_sms?useUnicode=true&characterEncoding=utf-8
#     #     driver-class-name: com.mysql.cj.jdbc.Driver
#     cloud:
#         nacos:
#             username: nacos
#             password: nacos
#             # discovery:
#             #     server-addr: 127.0.0.1:8848
#             config:
#                 server-addr: 127.0.0.1:8848
#                 namespace: c045de13-5652-4ae2-b618-b22b088c51b6
#                 group: dev
#                 file-extension: properties
#                 extension-configs:
#                 - data-id: datasource.yml
#                   group: dev
#                   refresh: true
#                 - data-id: mybatis.yml
#                   group: dev
#                   refresh: true
#                 - data-id: other.yml
#                   group: dev

#     config:
#         import:
#             - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
            
# # mybatis-plus:
# #     # 告诉 Mybatis-Plus, sql映射文件位置
# #     mapper-locations: classpath:mapper/**/*.xml
# #     global-config:
# #         db-config:
# #             # 配置自增主键
# #             id-type:  auto

# # # 配置用户信息
# # coupon:
# #     user:
# #         name: akkkkltl
# #         age: 18
spring:
    application:
        name: mall-coupon
    config:
        import:
            - nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}?group=${spring.cloud.nacos.config.group}&refreshEnabled=true
            - nacos:datasource.yml?group=${spring.cloud.nacos.config.group}&refreshEnabled=true
            - nacos:mybatis.yml?group=${spring.cloud.nacos.config.group}&refreshEnabled=true
            - nacos:other.yml?group=${spring.cloud.nacos.config.group}&refreshEnabled=true
    cloud:
        nacos:
            username: nacos
            password: nacos
            config:
                server-addr: 127.0.0.1:8848
                namespace: c045de13-5652-4ae2-b618-b22b088c51b6
                group: dev
                file-extension: yml
                # extension-configs:
                # - data-id: datasource.yml
                #   group: dev
                #   refresh: true
                # - data-id: mybatis.yml
                #   group: dev
                #   refresh: true
                # - data-id: other.yml
                #   group: dev
                #   refresh: true
    