server:
  port: 9000

spring:
  application:
      name: mall-order
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/mall_oms?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  # 告诉 Mybatis-Plus, sql映射文件位置
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
      db-config:
          # 配置自增主键
          id-type:  auto